INSERT INTO accounts VALUES (1,'test-only-hash','0900000001',NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO addresses VALUES (1,1,'Test address',CURRENT_TIMESTAMP);
INSERT INTO roles VALUES (1,'fixture-role','Fixture role',NULL);
INSERT INTO permissions VALUES (1,'fixture-permission','Fixture permission');
INSERT INTO account_roles VALUES (1,1);
INSERT INTO role_permissions VALUES (1,1);
INSERT INTO categories VALUES (1,NULL,'Root');
INSERT INTO brands VALUES (1,'Fixture brand');
INSERT INTO size_systems VALUES (1,'fixture-size-system','Fixture system');
INSERT INTO size_values VALUES (1,1,'M','Medium',1);
INSERT INTO colors VALUES (1,'fixture-color','Fixture color');
INSERT INTO products VALUES (1,1,1,1,'Fixture product',NULL,NULL,NULL,NULL,NULL,100.00,'fixture-status',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO product_images VALUES (1,1,'https://example.invalid/test.png',NULL);
INSERT INTO product_variants VALUES (1,1,1,1,NULL,NULL,'fixture-status',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO carts VALUES (1,1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO cart_items VALUES (1,1,1,1);
INSERT INTO vouchers VALUES (1,'fixture-voucher');
INSERT INTO orders VALUES (1,'fixture-order',1,'0900000001',NULL,'Test address',100.00,0.00,30000.00,30100.00,NULL,'PENDING',NULL,NULL,NULL,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO order_items VALUES (1,1,1,'Historical product',NULL,'M','Historical color',100.00,1,100.00);
INSERT INTO payments VALUES (1,'UNPAID',30100.00,0.00,0.00,NULL,NULL,NULL,NULL);
INSERT INTO shipping_infos VALUES (1,'fixture-mode',NULL);
INSERT INTO suppliers VALUES (1,'Fixture supplier',NULL,NULL,NULL,'fixture-status',NULL);
INSERT INTO goods_receipts VALUES (1,'fixture-receipt',1,'DRAFT',CURRENT_DATE,1,NULL,NULL,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO goods_receipt_items VALUES (1,1,1,2);
INSERT INTO inventories VALUES (1,10,CURRENT_TIMESTAMP);
INSERT INTO inventory_transactions VALUES (1,1,10,'OPENING_STOCK',NULL,NULL,1,NULL,CURRENT_TIMESTAMP);
INSERT INTO audit_logs VALUES (1,1,'fixture.action','fixture','1',NULL,CURRENT_TIMESTAMP);
INSERT INTO content_pages VALUES (1,'fixture-page','Fixture page','Fixture content',1,CURRENT_TIMESTAMP);
