spring.application.name=fido-backend
spring.profiles.default=dev
spring.config.import=optional:file:.env[.properties]
server.port=${SERVER_PORT:8080}
spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.time_zone=UTC
management.endpoints.web.exposure.include=health,info
springdoc.swagger-ui.path=/swagger-ui.html
